DESC TABLE staging_management.integrations.monitoreo_ingesta_staging
;

ALTER TABLE staging_management.integrations.monitoreo_ingesta_staging
    ALTER COLUMN NOMBRE_TABLA SET DATA TYPE VARCHAR(200);

select * from staging_management.integrations.monitoreo_ingesta_staging
;

LEFT JOIN SAPPRD.KONV KONV_1
ON KONV_1."KNUMV" = "SILVER_VENTAS_SAP"."NUMERO_DE_CONDICION"
  AND KONV_1."KPOSN" = "SILVER_VENTAS_SAP"."POSICION"
  AND KONV_1."MANDT" = "SILVER_VENTAS_SAP"."MANDANTE"
  AND KONV_1."KSCHL" = 'ZPRE'
  AND KONV_1."KINAK" = 'NA'
LEFT JOIN SAPPRD..KONV KONV_2 ON KONV_2."KNUMV" = "SILVER_VENTAS_SAP"."NUMERO_DE_CONDICION"
  AND KONV_2."KPOSN" = "SILVER_VENTAS_SAP"."POSICION"
  AND KONV_2."MANDT" = "SILVER_VENTAS_SAP"."MANDANTE"
  AND KONV_2."KSCHL" = 'PB00'
  AND KONV_2."KINAK" = 'NA'

'2025-01-28',
'2025-05-07',
'2025-08-11',
'2025-08-12',
'2025-08-20',
'2025-08-21',
'2025-08-27'
; 


  LEFT JOIN (
  SELECT
    STM_MSEG."VBELN_IM",
    STM_MSEG."VBELP_IM",
    STM_MSEG."MATNR",
    STM_MSEG."BWART",
    STM_MSEG."SAKTO"
  FROM (
    SELECT
      STM_MSEG."VBELN_IM",
      STM_MSEG."VBELP_IM",
      STM_MSEG."MATNR",
      STM_MSEG."BWART",
      STM_MSEG."SAKTO",
      STM_MSEG."MBLNR",
      ROW_NUMBER() OVER (
        PARTITION BY STM_MSEG."VBELN_IM", STM_MSEG."VBELP_IM", STM_MSEG."MATNR"
        ORDER BY STM_MSEG."MBLNR" DESC
      ) AS rn
    FROM "DEV_BRONZE_M"."BRONZE_STAGING"."STM_MSEG" 
    WHERE STM_MSEG."MBLNR" IS NOT NULL
  ) x
  WHERE rn = 1
) "MSEG_M"
  ON "MSEG_M"."VBELN_IM" = "SILVER_VENTAS_SAP"."ID_ENTREGA"   -- VGBEL
 AND "MSEG_M"."VBELP_IM" = "SILVER_VENTAS_SAP"."VGPOS"    -- VGPOS
 AND "MSEG_M"."MATNR"    = "SILVER_VENTAS_SAP"."ID_SKU_ORIGEN"