Select 
PERIODO, 
ID_SOCIEDAD_ORIGEN,
SUM(LITROS_VENDIDOS) 
from test_silver.comercial.silver_venta_neta_corp
where id_pais = 'PE'
AND PERIODO = '202501'
GROUP BY PERIODO
; 

Select 
* 
from test_silver.comercial.silver_venta_neta_corp
WHERE ID
LIMIT 10
; 

SELECT * 
FROM STAGING_PE_CH.SQL_FABRIC.VENTA VT
LEFT JOIN STAGING_PE_CH.SQL_FABRIC.CO CO
ON VT.IDDPT = CO.IDDPT ; 

SELECT DISTINCT 
PAIS,
--SOCIEDAD, 
REGION
FROM STAGING_PE_CH.SQL_FABRIC.CO
ORDER BY PAIS ASC; 

SELECT DISTINCT 
PAIS, 
REGION -- SELECT * 
FROM  STAGING_PE_CH.SQL_FABRIC.SEDE
ORDER BY PAIS; 

SELECT 
 TO_CHAR(TO_DATE("STG_VENTA"."IDFECONTABILIZACION", 'YYYY-MM-DD'), 'YYYYMM') AS MES,
        S.REGION,
	   SUM(V.Volumen_Venta) AS Litros
     --   SUM(V.Cajas_Venta) AS Cajas
    FROM STAGING_PE_CH.SQL_FABRIC.VENTA V
--	LEFT JOIN Dim_CO O ON O.idDpt =V.idDpt
-- LEFT JOIN Dim_Producto P ON V.idMaterial = P.idProducto
LEFT JOIN STAGING_PE_CH.SQL_FABRIC.CLIENTE C ON V.IdCliente = C.IdCliente
LEFT JOIN STAGING_PE_CH.SQL_FABRIC.SEDE S ON C.Sede = S.Sede
-- LEFT JOIN Dim_Ruta R ON C.idRuta = R.IdRuta
-- LEFT JOIN Dim_Canal I ON I.idCSG=C.idCSG
-- LEFT JOIN Dim_Ubigeo U	ON C.idUbigeo = U.idLugar
    WHERE 
        CAST(CAST(V.IDFECONTABILIZACION AS VARCHAR) AS DATE) >= '2025-01-01' --AND '2025-12-31'

   GROUP BY 
TO_CHAR(TO_DATE("STG_VENTA"."IDFECONTABILIZACION", 'YYYY-MM-DD'), 'YYYYMM'),
        S.REGION--,
; 

SELECT * FROM STAGING_PE_CH.SQL_FABRIC.CO; 
SELECT * FROM STAGING_PE_CH.SQL_FABRIC.SEDE; 
SELECT * FROM STAGING_PE_CH.SQL_FABRIC.VENTA LIMIT 10; 

SELECT  
TO_VARCHAR(TO_DATE(TO_VARCHAR("VENTA"."IDFECONTABILIZACION"), 'YYYYMMDD'), 'YYYYMM') AS PERIODO
FROM STAGING_PE_CH.SQL_FABRIC.VENTA LIMIT 10; 


    SELECT 
        TO_VARCHAR(TO_DATE(TO_VARCHAR(V.IDFECONTABILIZACION), 'YYYYMMDD'), 'YYYYMM') AS PERIODO,
        S.REGION AS REGION,
        SUM(V.VOLUMEN_VENTA) AS Litros
    FROM STAGING_PE_CH.SQL_FABRIC.VENTA V
  LEFT JOIN STAGING_PE_CH.SQL_FABRIC.PRODUCTOS P ON V.IDMATERIAL = P.IDPRODUCTO
  LEFT JOIN STAGING_PE_CH.SQL_FABRIC.CO O ON O.IDDPT =V.IDDPT
  LEFT JOIN STAGING_PE_CH.SQL_FABRIC.CLIENTE C ON V.IDCLIENTE = C.IDCLIENTE
  LEFT JOIN STAGING_PE_CH.SQL_FABRIC.SEDE S ON C.SEDE = S.SEDE
    WHERE 
        TO_VARCHAR(TO_DATE(TO_VARCHAR(V.IDFECONTABILIZACION), 'YYYYMMDD'), 'YYYYMM') >= '202510' --AND '2025-12-31'
	--	AND Pais='PE'
   GROUP BY 
        TO_VARCHAR(TO_DATE(TO_VARCHAR(V.IDFECONTABILIZACION), 'YYYYMMDD'), 'YYYYMM') , S.REGION --,S.CentroGestion,C.IdCliente,C.RazonSocial2
   ORDER BY TO_VARCHAR(TO_DATE(TO_VARCHAR(V.IDFECONTABILIZACION), 'YYYYMMDD'), 'YYYYMM') ASC
	
;

WITH Ventas AS (
    SELECT 
        /* Mes numérico (1–12) a partir de IDFECONTABILIZACION */
        TO_NUMBER(TO_CHAR(TO_DATE(TO_VARCHAR(V.IDFECONTABILIZACION), 'YYYYMMDD'), 'MM')) AS MES,
        S.REGION AS REGION,
        SUM(V.VOLUMEN_VENTA) AS LITROS
        -- sum(V.CAJAS_VENTA) AS CAJAS
    FROM STAGING_PE_CH.SQL_FABRIC.VENTA V
    LEFT JOIN STAGING_PE_CH.SQL_FABRIC.PRODUCTOS P ON TRIM(V.IDMATERIAL) = TRIM(P.IDPRODUCTO)
    LEFT JOIN STAGING_PE_CH.SQL_FABRIC.CO O ON TRIM(O.IDDPT) = TRIM(V.IDDPT)
    ///    AGREGAR ESTOS 2 JOIN A LA TABLA SILVER  /////////////// 
    ///    AÑADIR REFION ( PARA DIM SESE   )       //////////////7 
    ///    CENTRO DE GESTION - SEDE                ///////////////
    LEFT JOIN STAGING_PE_CH.SQL_FABRIC.CLIENTE C ON TRIM(V.IDCLIENTE) = TRIM(C.IDCLIENTE)
    LEFT JOIN STAGING_PE_CH.SQL_FABRIC.SEDE S ON TRIM(C.SEDE) = TRIM(S.SEDE)
    WHERE 
        TO_DATE(TO_VARCHAR(V.IDFECONTABILIZACION), 'YYYYMMDD') >= DATE '2025-01-01'
        -- AND PAIS = 'PE'
    GROUP BY 
        MES, 
        S.REGION
)
SELECT 
    REGION,
    COALESCE("1",  0) AS ENE,
    COALESCE("2",  0) AS FEB,
    COALESCE("3",  0) AS MAR,
    COALESCE("4",  0) AS ABR,
    COALESCE("5",  0) AS MAY,
    COALESCE("6",  0) AS JUN,
    COALESCE("7",  0) AS JUL,
    COALESCE("8",  0) AS AGO,
    COALESCE("9",  0) AS SEP,
    COALESCE("10", 0) AS OCT,
    COALESCE("11", 0) AS NOV
FROM Ventas
PIVOT (
    SUM(LITROS) FOR MES IN (1,2,3,4,5,6,7,8,9,10,11)
) AS PV
ORDER BY REGION DESC;

SELECT * FROM TEST_SILVER.COMERCIAL.SILVER_VENTA_NETA_CORP
WHERE ID_PAIS = 'PE' 
LIMIT 100;
/////////// CUASRAR REPROCES A 2 MESES //////////// 


SELECT 
    /* Mes numérico (1–12) a partir de IDFECONTABILIZACION */
    TO_VARCHAR(TO_DATE(TO_VARCHAR("VENTA"."IDFECONTABILIZACION"), 'YYYYMMDD'), 'YYYYMM') AS PERIDO,
    SUM(VOLUMEN_VENTA) AS LITROS,
    sum(cajas_venta) as cajas -- SELECT * 
FROM STAGING_PE_CH.SQL_FABRIC.VENTA 
where TO_VARCHAR(TO_DATE(TO_VARCHAR("VENTA"."IDFECONTABILIZACION"), 'YYYYMMDD'), 'YYYYMM') >= '202501' 
GROUP BY TO_VARCHAR(TO_DATE(TO_VARCHAR("VENTA"."IDFECONTABILIZACION"), 'YYYYMMDD'), 'YYYYMM')
ORDER BY PERIDO ASC
;