WITH VENTAS_br_totoal as (
SELECT CONCAT(
    "STG_VIEW_VENDASBR_ML"."ID_NF",
    '-',
    "STG_VIEW_VENDASBR_ML"."CONSUMERS_ID",
    '-',
    "STG_VIEW_VENDASBR_ML"."ROUTEID",
    '-',
    TO_DATE("STG_VIEW_VENDASBR_ML"."SALESDATE"),
    '-',
    "STG_VIEW_VENDASBR_ML"."SALESCHANNEL",
    '-',
    "STG_VIEW_VENDASBR_ML"."SKUCODE"
  ) AS "ID_VENTA",
  'NA' AS "ID_PEDIDO",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."ID_NF") AS "ID_ENTREGA",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."CONSUMERS_ID") AS "ID_CLIENTE_ORIGEN",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."SALESCHANNEL") AS "ID_CANAL",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."COD_RAMO") AS "ID_SUBCANAL",
  CONCAT(
    'BR',
    '-',
    CAST("STG_VIEW_VENDASBR_ML"."SOCIEDAD" AS STRING)
  ) AS "ID_SOCIEDAD",
  'BR' AS "ID_PAIS",
  CAST("STG_VIEW_VENDASBR_ML"."SOCIEDAD" AS STRING) AS "ID_SOCIEDAD_ORIGEN",
  CAST("STG_VIEW_VENDASBR_ML"."SOCIEDAD" AS STRING) AS "ID_CENTRO_ORIGEN",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."SKUCODE") AS "ID_SKU_ORIGEN",
  COALESCE(
    "STG_VIEW_PRODUTOS_ML"."MEMBERNAME",
    "STG_VIEW_PROD_ISM"."PROD_DESC",
    'NA'
  ) AS "NOM_SKU",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."ROUTEID") AS "ID_VENDEDOR",
  'NA' AS "ID_DISTRIBUIDOR",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."ROUTEID") AS "ID_RUTA",
  TO_VARCHAR("STG_VIEW_VENDASBR_ML"."ID_NF") AS "ID_FACTURA_VENTA",
  'NA' AS "ID_FACTURA_RECHAZO",
  SUM(
    COALESCE("STG_VIEW_VENDASBR_ML"."QTY_VENDA", 0) * COALESCE("STG_VIEW_PRODUTOS_ML"."FACTOR_CX", 0)
  ) AS "CANTIDAD_VENDIDA_UN",
  0 AS "CANTIDAD_RECHAZO_UN",
  SUM(
    COALESCE("STG_VIEW_VENDASBR_ML"."QTY_BONIF", 0) * COALESCE("STG_VIEW_PRODUTOS_ML"."FACTOR_CX", 0)
  ) AS "CANTIDAD_BONIFICADA_UN",
  SUM("STG_VIEW_VENDASBR_ML"."VLR_VENTA") AS "MONTO_VENTA",
  0 AS "MONTO_RECHAZO",
  SUM("STG_VIEW_VENDASBR_ML"."VLR_VENTA") AS "MONTO_VENTA_NETA",
  SUM(
    "STG_VIEW_VENDASBR_ML"."ICMS" + "STG_VIEW_VENDASBR_ML".IPI + "STG_VIEW_VENDASBR_ML"."SUBSTITUTO" + "STG_VIEW_VENDASBR_ML"."COFINS" + "STG_VIEW_VENDASBR_ML"."PIS"
  ) AS "IMPUESTO_TOTAL_VENTA",
  SUM(
    COALESCE("STG_VIEW_VENDASBR_ML"."QTY_VENDA", 0) * COALESCE("STG_VIEW_PRODUTOS_ML"."FACTOR_CX", 0)
  ) AS "VENTA_NETA_UN",
  0 AS "IMPUESTO_TOTAL_RECHAZO",
  SUM(
    "STG_VIEW_VENDASBR_ML"."ICMS" + "STG_VIEW_VENDASBR_ML".IPI + "STG_VIEW_VENDASBR_ML"."SUBSTITUTO" + "STG_VIEW_VENDASBR_ML"."COFINS" + "STG_VIEW_VENDASBR_ML"."PIS"
  ) AS "IMPUESTO_TOTAL_NETA",
  SUM(
    COALESCE("STG_VIEW_VENDASBR_ML"."QTY_VENDA", 0) * COALESCE("STG_VIEW_PRODUTOS_ML"."LITRAGEM", 0)
  ) AS "LITROS_VENDIDOS",
  SUM(
    COALESCE("STG_VIEW_VENDASBR_ML"."QTY_VENDA", 0) * COALESCE("STG_VIEW_PRODUTOS_ML"."LITRAGEM", 0)
  ) AS "LITROS_VENDIDOS_NETOS",
  SUM(
    (
      COALESCE("STG_VIEW_VENDASBR_ML"."QTY_BONIF", 0) * COALESCE("STG_VIEW_PRODUTOS_ML"."LITRAGEM", 0)
    )
  ) AS "LITROS_BONIFICADOS",
  SUM("STG_VIEW_VENDASBR_ML"."QTY_VENDA") AS "PQT_VENDIDOS",
  SUM("STG_VIEW_VENDASBR_ML"."QTY_VENDA") AS "PQT_NETOS",
  SUM("STG_VIEW_VENDASBR_ML"."QTY_BONIF") AS "PQT_BONIFICADOS",
  TO_DATE("STG_VIEW_VENDASBR_ML"."SALESDATE") AS "FECHA",
  TO_CHAR("STG_VIEW_VENDASBR_ML"."SALESDATE", 'YYYYMM') AS "PERIODO",
  "STG_VIEW_VENDASBR_ML"."D_NEGOCIO" AS "D_NEGOCIO",
  TO_DATE("STG_VIEW_VENDASBR_ML"."DATA_LIB") AS "FECHA_LIQUIDACION",
  "STG_VIEW_VENDASBR_ML"."VLR_DESC" AS "MONTO_DESCUENTO",
  "STG_VIEW_VENDASBR_ML"."SVR" AS "SVR",
  "STG_VIEW_VENDASBR_ML"."ICMS" AS "ICMS",
  "STG_VIEW_VENDASBR_ML"."IPI" AS "IPI",
  "STG_VIEW_VENDASBR_ML"."SUBSTITUTO" AS "SUBSTITUTO",
  "STG_VIEW_VENDASBR_ML"."COFINS" AS "COFINS",
  "STG_VIEW_VENDASBR_ML"."PIS" AS "PIS", 
  "STG_VIEW_VENDASBR_ML".D_SITUACAO as D_SITUACAO
FROM DEV_BRONZE_M.COMERCIAL."STG_VIEW_VENDASBR_ML" STG_VIEW_VENDASBR_ML
  LEFT JOIN DEV_BRONZE_M.COMERCIAL."STG_VIEW_PRODUTOS_ML" "STG_VIEW_PRODUTOS_ML" ON STG_VIEW_PRODUTOS_ML."SOCIEDAD" = STG_VIEW_VENDASBR_ML."SOCIEDAD"
  AND "STG_VIEW_PRODUTOS_ML"."SKU" = "STG_VIEW_VENDASBR_ML"."SKUCODE"
  LEFT JOIN DEV_BRONZE_M.COMERCIAL."STG_VIEW_PROD_ISM" "STG_VIEW_PROD_ISM" ON "STG_VIEW_PRODUTOS_ML"."SKU" = "STG_VIEW_PROD_ISM"."PROD_ID"
GROUP BY "STG_VIEW_VENDASBR_ML"."ID_NF",
  "STG_VIEW_VENDASBR_ML"."SKUCODE",
  "STG_VIEW_VENDASBR_ML"."CONSUMERS_ID",
  "STG_VIEW_VENDASBR_ML"."SALESCHANNEL",
  "STG_VIEW_VENDASBR_ML"."SOCIEDAD",
  "STG_VIEW_VENDASBR_ML"."COD_RAMO",
  "STG_VIEW_VENDASBR_ML"."ROUTEID",
  "STG_VIEW_VENDASBR_ML"."SALESDATE",
  "STG_VIEW_VENDASBR_ML"."D_NEGOCIO",
  "STG_VIEW_PRODUTOS_ML"."UNIDAD_NEGOCIO",
  "STG_VIEW_PROD_ISM"."PROD_DESC",
  "STG_VIEW_PRODUTOS_ML"."MEMBERNAME",
  CONCAT('BR-', CAST("STG_VIEW_VENDASBR_ML"."SOCIEDAD" AS STRING)),
  "STG_VIEW_VENDASBR_ML"."DATA_LIB",
  "STG_VIEW_VENDASBR_ML"."VLR_DESC",
  "STG_VIEW_VENDASBR_ML"."SVR",
  "STG_VIEW_VENDASBR_ML"."ICMS",
  "STG_VIEW_VENDASBR_ML"."IPI",
  "STG_VIEW_VENDASBR_ML"."SUBSTITUTO",
  "STG_VIEW_VENDASBR_ML"."COFINS",
  "STG_VIEW_VENDASBR_ML"."PIS", 
  "STG_VIEW_VENDASBR_ML".D_SITUACAO
)
select 
SUM(LITROS_VENDIDOS) as LITROS_VENDIDOS,
SUM(PQT_VENDIDOS) AS PQT_VENDIDOS,
SUM(MONTO_VENTA) AS MONTO_VENTA,
D_SITUACAO, 
D_NEGOCIO,
SVR,
PERIODO
from VENTAS_br_totoal
WHERE PERIODO >= '202501'
GROUP BY D_SITUACAO, D_NEGOCIO, SVR, PERIODO
ORDER BY PERIODO, SVR, D_SITUACAO, D_NEGOCIO ASC 

; 

select * from STAGING_BR.ORACLE."VIEW_VENDASBR_ML"
where id_nf = 3330058
--and sociedad = 53 
--and consumers_id = 568538 
--and skucode = 58
; 


select 
SUM(LITROS_VENDIDOS) as LITROS_VENDIDOS,
SUM(PQT_VENDIDOS) AS PQT_VENDIDOS,
SUM(MONTO_VENTA) AS MONTO_VENTA,
D_NEGOCIO,
SVR,
PERIODO
FROM TEST_SILVER.COMERCIAL.SILVER_VENTA_NETA_CORP
WHERE PERIODO >= '202501'
GROUP BY D_NEGOCIO, SVR, PERIODO
ORDER BY PERIODO, SVR, D_NEGOCIO ASC 
; 

SELECT DISTINCT SVR FROM TEST_SILVER.COMERCIAL.SILVER_VENTA_NETA_CORP
WHERE ID_PAIS = 'BR'
ORDER BY SVR ASC
; 
SELECT DISTINCT SVR FROM STAGING_BR.ORACLE.VIEW_VENDASBR_ML
ORDER BY SVR ASC
; 

SELECT DISTINCT SVR FROM TEST_BRONZE.COMERCIAL.STG_VIEW_VENDASBR_ML
ORDER BY SVR ASC
; 

SELECT DISTINCT SVR FROM TEST_BRONZE.COMERCIAL.VENTAS_NETA_BR
ORDER BY SVR ASC
; 
