            SELECT "ID_VENTA", COUNT(*)
            FROM "TEST_BRONZE"."COMERCIAL"."CTE_VENTAS_NETAS_BR" 
            GROUP BY "ID_VENTA"
            HAVING COUNT(*) > 1 ; 
SELECT * FROM"TEST_BRONZE"."COMERCIAL"."CTE_VENTAS_NETAS_BR" 
WHERE  "ID_VENTA" = '233899-583976-1301-2023-10-28-1-66';

-- 2 MONTO VENTA }


//////////// VENTA NETA 
            SELECT "ID_VENTA_NETA", COUNT(*)
            FROM "TEST_SILVER"."COMERCIAL"."SILVER_VENTA_NETA_CORP" 
            GROUP BY "ID_VENTA_NETA"
            HAVING COUNT(*) > 1
;
///////////// VALIDACION DE DATOS 

SELECT * FROM TEST_BRONZE.COMERCIAL.VENTAS_NETA_BR 
LIMIT 10; 

SELECT 
PERIODO, 
D_NEGOCIO, 
SVR,
SUM(LITROS_VENDIDOS), 
SUM(LITROS_RECHAZADOS), 
SUM(LITROS_BONIFICADOS), 
SUM(MONTO_VENTA), 
SUM(MONTO_RECHAZO), 
SUM(MONTO_VENTA_NETA), 
SUM(PQT_VENDIDOS), 
SUM(PQT_RECHAZADOS), 
SUM(PQT_NETOS), 
SUM(PQT_BONIFICADOS), 
SUM(MONTO_DESCUENTO)
FROM TEST_BRONZE.COMERCIAL.VENTAS_NETA_BR
GROUP BY PERIODO, SVR, D_NEGOCIO 
ORDER BY PERIODO, SVR, D_NEGOCIO ; 

SELECT DISTINCT D_NEGOCIO FROM TEST_BRONZE.COMERCIAL.VENTAS_NETA_BR;

    SUM(v.icms)            AS icms,
    SUM(v.ipi)           AS ipi,
    SUM(v.substituto)      AS substituto,
    SUM(v.cofins)          AS cofins,
    SUM(v.pis)             AS pis,
    SUM(v.d_situacao)      AS d_situacao