SELECT 
    YEAR( CAST(FKDAT AS DATE))*100 + MONTH(CAST(FKDAT AS DATE)) AS PERIODO,
    PSTYV,
    CASE 
        WHEN VBRP.PSTYV IN ('TAN', 'ZTAD','TAQ','KEN','ZBTA') THEN 'VENTA BRUTA'
        WHEN VBRP.PSTYV IN ('ZG2N', 'ZG3N') THEN 'RECHAZO'
        WHEN VBRP.PSTYV IN ('TANN','ZTND') THEN 'BONIFICACIONES'
        ELSE 'OTROS'
    END AS TIPO_VENTA,
    VBRP.MATNR AS SKU,
    VBRK.VTWEG AS CANAL,
    VBRK.VKORG AS CENTRO,
    SUM(VOLUM)/1000 AS LITROS,
    SUM(FKLMG) AS UNIDADES -- SELECT FKDAT
FROM STAGING_RD_HT_GT.SAP.VBRP VBRP
INNER JOIN --SELECT YEAR( CAST(FKDAT AS DATE))*100 + MONTH(CAST(FKDAT AS DATE)) FROM
    STAGING_RD_HT_GT.SAP.VBRK VBRK
ON 
    VBRK."VBELN" = VBRP."VBELN" 
    AND 
    VBRK.BUKRS IN ('1000')
GROUP BY 
    SKU,
    PSTYV,
    PERIODO,
    TIPO_VENTA,
    CANAL,
    CENTRO
;

///////////////////////// VERSION 2 //////////// 
SELECT 
    YEAR( CAST(VBRK.FKDAT AS DATE))*100 + MONTH(CAST(VBRK.FKDAT AS DATE)) AS PERIODO,
    PSTYV,
    CASE 
        WHEN VBRP.PSTYV IN ('TAN', 'ZTAD','TAQ','KEN','ZBTA') THEN 'VENTA BRUTA'
        WHEN VBRP.PSTYV IN ('ZG2N', 'ZG3N') THEN 'RECHAZO'
        WHEN VBRP.PSTYV IN ('TANN','ZTND') THEN 'BONIFICACIONES'
        ELSE 'OTROS'
    END AS TIPO_VENTA,
    VBRP.MATNR AS SKU,
    VBRK.VTWEG AS CANAL,
    VBRK.VKORG AS CENTRO,
    CASE 
        WHEN VBRP.VOLEH = 'ML' THEN SUM(VBRP.VOLUM/1000)
        WHEN VBRP.VOLEH = 'L' THEN SUM(VBRP.VOLUM)
        ELSE 0
    END AS LITROS, 
    --SUM(VOLUM)/1000 AS LITROS,
    SUM(VBRP.FKLMG) AS UNIDADES,
    SUM(VBRP.NETWR * VBRK.KURRF) AS MONTO_NETA_MONEDAD_LOCAL
     -- SELECT FKDAT
FROM STAGING_RD_HT_GT.SAP.VBRP VBRP
INNER JOIN --SELECT YEAR( CAST(FKDAT AS DATE))*100 + MONTH(CAST(FKDAT AS DATE)) FROM
    STAGING_RD_HT_GT.SAP.VBRK VBRK
ON 
    VBRK."VBELN" = VBRP."VBELN" 
    AND 
    VBRK.BUKRS IN ('1000')
WHERE VBRK.FKDAT >= '2025-01-01'
GROUP BY 
    SKU,
    PSTYV,
    PERIODO,
    TIPO_VENTA,
    CANAL,
    CENTRO, 
    VBRP.VOLEH
;

